mainapp/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static  # new

urlpatterns = [
    # home path's
    path("", views.home, name="homepage"),
    path("register/", views.Register, name="Registeruser"),
    path("registercustomer/", views.CustomerRegister, name="Registercustomer"),
    path("invoice/", views.invoice, name="invoice"),
    path("proformatoinvoice/<int:id>", views.proforma_to_invoice, name="proformatoinvoice",),
    path("deliverychallan/", views.deliverychallan, name="deliverychallan"),
    path("installationReport/", views.installation_Report, name="installationReport"),
    path("contractorbill/", views.contractorbill, name="contractorbill"),
    path("createquotation/", views.createQuotation, name="createquotation"),
    path("proformainvoice/", views.proformainvoice, name="proformainvoice"),
    path("addproduct/", views.addproduct, name="addproduct"),
    path("checkUserName/", views.checkUserName, name="checkUserName"),
    path("profile/", views.dealerProfile, name="UserProfile"),
    

    # view Path's
    path("viewcustomers/", views.vieweditcustomer, name="vieweditcustomer"),
    path("viewdealer/", views.viewdealer, name="viewdealer"),
    path("vieweditproducts/", views.vieweditproducts, name="vieweditproducts"),
    path("vieweinvoices/", views.vieweinvoices, name="vieweinvoices"),
    path("viewproinvoices/",views.viewproinvoices, name="viewproinvoices"),
    path("viewequotations/", views.viewequotations, name="viewequotations"),
    path("viewinstallationreport/", views.view_installation_report, name="viewinstallationreport"),
    path("vieweditdealer/",views.vieweditdealer,name="vieweditdealer",),
    path("viewdeliverychallan/", views.viewdeliverychallan, name="viewdeliverychallan"),
    

    # edit path's
    path("editingdealer/<int:id>", views.editingdealer, name="editingdealer"),
    path("editingproduct/<int:hsn>", views.editingproduct, name="editingproduct"),
    path("editinginvoice/<int:id>", views.editinginvoice, name="editinginvoice",),
    path("editingproformainvoice/<int:id>", views.editing_proforma_invoice, name="editingproformainvoice",),
    path("editingcustomer/<int:id>", views.editingcustomer, name="editingcustomer",),
    path("editinvoices/", views.editinvoices, name="editinvoices/"),


    # delete path's
    path("deletedealer/", views.deletedealer, name="deletedealer"),
    path("deletingdealer/<int:id>", views.deletingdealer, name="deletingdealer"),
    path("deleteproduct/<int:hsn>", views.deleteproduct, name="deleteproduct"),

    # cloning path's
    path("cloninginvoice/<int:id>", views.cloninginvoice, name="cloninginvoice",),
    path("cloningproformainvoice/<int:id>", views.cloning_proforma_invoice, name="cloningproformainvoice",),
    
    # update path's
    path("updatingproduct/<int:id>", views.updatingproduct, name="updatingproduct"),
    path("updatingdealer/<int:id>", views.updatingdealer, name="updatingdealer"), 

    # remove path's
    path("removecustomer/", views.removecustomer, name="removecustomer",),
    path("removeinvoices/", views.removeinvoices, name="removeinvoicess",),
    path("removingdealer/<int:id>", views.removingdealer, name="removingdealer"),
    path("removingcustomer/<int:id>", views.removingcustomer, name="removingcustomer"),
    
    # database path's
    path("addtoinvoicedb/", views.addtoinvoicedb, name="addtoinvoicedbs"),
    path("invoicegetallprod/", views.invoicegetallprod, name="invoicegetallprod"),
    path(
        "invoice/gettaxdetailofstate/",
        views.gettaxdetailofstate,
        name="gettaxdetailofstate",
    ),
    path(
        "vieweinvoices/gettaxdetailofstate/",
        views.gettaxdetailofstate,
        name="vieweinvoices-gettaxdetailofstate",
    ),
    path(
        "createquotation/gettaxdetailofstate/",
        views.gettaxdetailofstate,
        name="createquotation-gettaxdetailofstate",
    ),
    path(
        "deliverychallan/gettaxdetailofstate/",
        views.gettaxdetailofstate,
        name="createquotation-gettaxdetailofstate",
    ),
    path(
        "viewproinvoices/gettaxdetailofstate/",
        views.gettaxdetailofstate,
        name="viewproinvoices-gettaxdetailofstate",
    ),
    path(
        "invoicegetallprodcol/",
        views.invoicegetallprodcol,
        name="invoicegetallprodcol",
    ),
    path(
        "getdetailofselectedcustmor/",
        views.getdetailofselectedcustmor,
        name="getdetailofselectedcustmors",
    ),
    path(
        "updatingdealer/submitupdatedealer/",
        views.submitupdatedealer,
        name="submitupdatedealer",
    ),
    
   
    #Login and logout path's
    path(
        "login/", auth_views.LoginView.as_view(template_name="login.html"), name="login"
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="logout.html"),
        name="logout",
    ),
]
if settings.DEBUG:  # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

medprime/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),

]

mainapp/models.py
from django.db import models
from django.contrib.auth.models import User
from phone_field import PhoneField
from jsonfield import JSONField
from phonenumber_field.modelfields import PhoneNumberField


# Create your models here.

# Profile Model

class MyModel(models.Model):
    name = models.CharField(max_length=128)
    phone = PhoneField(blank=True, help_text='Contact phone number')

class SerialNumbercounter(models.Model):
    counter = models.IntegerField()

    def __str__(self):
        return f"{self.counter}"


class Profile(models.Model):
    geography = (("gujrat", "Inside Gujrat"), ("other", "Outside Gujrat"))
    market_segment = (
        ("medclg", "Medical College"),
        ("pathological", "Pathological Laboratories"),
        ("hospitals", "Hospitals"),
        ("medpro", "Medical Professionals"),
        ("sciclg", "Science College"),
        ("schools", "Schools"),
        ("rnd", "R&D Institues"),
        ("agriculture", "Agriculture"),
        ("veterinary", "Veterinary"),
        ("industrial", "Industrial"),
    )
    partnership_cat = (
        ("Level1", "Level 1"),
        ("Level2", "Level 2"),
        ("Level3", "Level 3"),
        ("Level4", "Level 4"),
    )
    legal_stus = (
        ("prlc", "Private Limited Company"),
        ("pulc", "Public Limited Company"),
        ("llp", "Limited Liability Partnership"),
        ("partner", "Partnership"),
        ("solepartner", "Sole Proprietorship"),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    address = models.TextField(blank=True)
    pincode = models.IntegerField(null=True, blank=True)
    telephone = PhoneNumberField(blank=True, null=True, help_text="Contact phone number")
    mobile = PhoneNumberField(blank=True, null=True, help_text="Contact mobile number")
    nameofcontact = models.CharField(max_length=100)
    contactparticulars = models.CharField(blank=True, max_length=100)
    legalstatus = models.CharField(blank=True, max_length=100, choices=legal_stus)
    gstno = models.CharField(blank=True, max_length=20)
    cinno = models.CharField(blank=True, max_length=20)
    panno = models.CharField(blank=True, max_length=20)
    shopactno = models.CharField(blank=True, max_length=20)
    businessgeography = models.CharField(blank=True, max_length=50, choices=geography)
    marketsegment = models.CharField(blank=True, max_length=50, choices=market_segment)
    currentproducts = models.TextField(blank=True)
    currentstaffstrength = models.IntegerField(null=True, blank=True)
    customershandledsofar = models.TextField(blank=True)
    salersturnover = models.IntegerField(null=True, blank=True)
    parternshipcat = models.CharField(
        blank=True, max_length=50, choices=partnership_cat
    )
    image = models.ImageField(default="default.png", upload_to="profile_pics")

    def __str__(self):
        return f"{self.user}"

    def __unicode__(self):
        return


class CustomerProfile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    customername = models.CharField(max_length=100)
    distributer = models.CharField(max_length=500)
    billingbuilding = models.CharField(max_length=50)
    billingarea= models.CharField(max_length=50)
    billinglandmark = models.CharField(max_length=50,blank=True, null=True)
    billingcountry = models.CharField(max_length=50)
    billingpincode = models.IntegerField()
    billingcity = models.CharField(max_length=50)
    billingstate = models.CharField(max_length=50)
    country = models.CharField(max_length=50)
    building = models.CharField(max_length=50)
    area= models.CharField(max_length=50)
    landmark= models.CharField(max_length=50,blank=True, null=True)
    pincode = models.IntegerField(blank=True)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    stateid = models.IntegerField(null=True)
    gst = models.CharField(blank=True, null=True, max_length=500)
    phone = PhoneNumberField(blank=True)

    def __str__(self):
        return f"{self.user}"

    def __unicode__(self):
        return self.customername


class Product(models.Model):

    name = models.CharField(max_length=150)
    description = models.TextField()
    price = models.IntegerField()
    HSN = models.IntegerField()
    tax = models.IntegerField()

    def __str__(self):
        return f"{self.name}"


class gsttable(models.Model):
    state = models.CharField(max_length=150)
    igst = models.BooleanField()
    cgst = models.BooleanField()
    sgst = models.BooleanField()

    def __str__(self):
        return self.state


class AllCounters(models.Model):

    name = models.CharField(max_length=150)
    counter = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.name


# Final invoice model
class taxInvoice(models.Model):
    invoiceid = models.IntegerField(null=True, blank=True)
    customerid = models.IntegerField(null=True, blank=True)
    creatorid = models.IntegerField(null=True, blank=True)
    creatorname = models.CharField(max_length=500, null=True, blank=True)
    updatorid = models.IntegerField(null=True, blank=True)
    customername = models.CharField(max_length=500)
    invoicedate = models.DateField(null=True, blank=True)
    terms = models.CharField(max_length=500, blank=True)
    duedate = models.DateField(null=True, blank=True)
    po = models.CharField(max_length=500, blank=True,null=True)
    items = JSONField( blank=True,null=True)
    customerdetails = JSONField( blank=True,null=True)
    shippingState = models.CharField(max_length=500, blank=True)
    subtotalamount = models.FloatField(null=True, blank=True)
    taxamount = models.FloatField(null=True, blank=True)
    adjustmentamount = models.FloatField(null=True, blank=True)
    adjustmenttype = models.CharField(max_length=500, blank=True)
    finalamount = models.FloatField(null=True, blank=True)
    signature = models.BooleanField(null=True, blank=True)

    def __str__(self):
        return f"{self.invoiceid}"


class invoicestorage(models.Model):
    invoiceid = models.IntegerField(null=True, blank=True)
    creatorid = models.IntegerField(null=True, blank=True)
    deletorid = models.IntegerField(null=True, blank=True)
    typeofchange = models.CharField(max_length=500, blank=True)

    def __str__(self):
        return str(self.invoiceid)


# Quotation model
# class quotationInvoice(models.Model):
#     quotationid = models.IntegerField()
#     customerid = models.IntegerField()
#     creatorid = models.IntegerField(null=True, blank=True)
#     updatorid = models.IntegerField(null=True, blank=True)
#     customername = models.CharField(max_length=500)
#     customeraddress = models.CharField(null=True, blank=True, max_length=500)
#     customerpincode = models.CharField(null=True, blank=True, max_length=500)
#     customerstate = models.CharField(null=True, blank=True, max_length=500)
#     customergst = models.CharField(null=True, blank=True, max_length=500)
#     customerplaceofsupply = models.CharField(null=True, blank=True, max_length=500)
#     quotationdate = models.DateField()
#     terms = models.CharField(max_length=500, blank=True)
#     exiprydate = models.DateField()
#     quotationnumber = models.IntegerField()
#     items = JSONField()
#     subtotalamount = models.FloatField(null=True, blank=True)
#     taxamount = models.FloatField(null=True, blank=True)
#     adjustmentamount = models.FloatField(null=True, blank=True)
#     finalamount = models.FloatField(null=True, blank=True)
#     signature = models.BooleanField(null=True, blank=True)

#     def __str__(self):
#         return f"{self.quotationid}"

class quotationInvoice(models.Model):
    quotationid = models.IntegerField(null=True, blank=True)
    customerid = models.IntegerField(null=True, blank=True)
    creatorid = models.IntegerField(null=True, blank=True)
    creatorname = models.CharField(max_length=500, null=True, blank=True)
    updatorid = models.IntegerField(null=True, blank=True)
    customername = models.CharField(max_length=500)
    quotationdate = models.DateField(null=True,blank=True)
    terms = models.CharField(max_length=500, blank=True)
    po = models.CharField(max_length=500, blank=True,null=True)
    items = JSONField( blank=True,null=True)
    customerdetails = JSONField( blank=True,null=True)
    shippingState = models.CharField(max_length=500, blank=True)
    subtotalamount = models.FloatField(null=True, blank=True)
    signature = models.BooleanField(null=True, blank=True)

    def __str__(self):
        return f"{self.quotationid}"


class quotationstorage(models.Model):
    quotationid = models.IntegerField(null=True, blank=True)
    creatorid = models.IntegerField(null=True, blank=True)
    deletorid = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.quotationid

class proformaInvoice(models.Model):
    invoiceid = models.IntegerField(null=True, blank=True)
    customerid = models.IntegerField(null=True, blank=True)
    creatorid = models.IntegerField(null=True, blank=True)
    creatorname = models.CharField(max_length=500, null=True, blank=True)
    updatorid = models.IntegerField(null=True, blank=True)
    customername = models.CharField(max_length=500)
    invoicedate = models.DateField(null=True, blank=True)
    terms = models.CharField(max_length=500, blank=True)
    subtotalamount = models.FloatField(null=True, blank=True)
    shippingState = models.CharField(max_length=500, blank=True)
    taxamount = models.FloatField(null=True, blank=True)
    subtotalamount = models.FloatField(null=True, blank=True)
    po = models.CharField(max_length=500, blank=True,null=True)
    items = JSONField( blank=True,null=True)
    customerdetails = JSONField( blank=True,null=True)
    finalamount = models.FloatField(null=True, blank=True)
    signature = models.BooleanField(null=True, blank=True)

    def __str__(self):
        return f"{self.invoiceid}"

mainapp/templates/product/addproduct.html
{% extends 'index.html' %}
{% load crispy_forms_tags %}
{% block content %}
{% for message in messages %}
<div style='color:black' class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
</div>
{% endfor %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">Add Customer</h6>
            </div>
            <div class="card-body">
                <form method="POST">
                    {% csrf_token %}
                    <div class='row'>
                        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 col-xl-6">
                    {{ productform.name|as_crispy_field }}
                </div>
                <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 col-xl-6">
                            <div id='for_HSN' class="form-group has-warning has-feedback">

                    {{ productform.HSN|as_crispy_field }}
                                    <span id='for_HSN_symbol' class="ti-reload form-control-feedback"></span>
                            </div>

                </div>
                </div>
                    <div class='row'>
                        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 col-xl-6">
                    {{ productform.price|as_crispy_field }}
                </div>
                <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 col-xl-6">
                    {{ productform.tax|as_crispy_field }}
                </div>
                </div>
                <div class='row'>
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">

                    {{ productform.description|as_crispy_field }}
                </div>
                </div>
                    <div class='row'>
                    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 col-xl-6">
                            <button id='submitForm' type="submit" class="btn btn-primary btn-flat btn-addon m-b-10 m-l-5"><i
                                    class="ti-plus"></i>Add Product </button>
                        </div>
                    </div>
                </form>
            </div>
          </div>
        </div>
        </div>
</div>




<script>
    $(document).ready(function() {
        // messages timeout for 10 sec 
     $("#for_HSN").on("keyup", function () {
    var input = $("#id_HSN").val()
    var string = 'SELECT "HSN" FROM public.mainapp_product where "HSN" = ' + input 
 document.getElementById('for_HSN').className = 'form-group has-warning has-feedback'
    document.getElementById('for_HSN_symbol').className = 'ti-reload form-control-feedback'

    $.get("/checkUserName/", { sqlParam: string }, function (data) {
        if (data.length != 0) {
            document.getElementById('for_HSN').className = 'form-group has-error has-feedback'
            document.getElementById('for_HSN_symbol').className = 'ti-close form-control-feedback'

        } else {
                document.getElementById('for_HSN').className = 'form-group has-success has-feedback'
                document.getElementById('for_HSN_symbol').className = 'ti-check form-control-feedback'
           
        }
    })

});

    });
</script>
{% endblock %}

mainapp/templates/product/allproducts.html
{% extends 'index.html' %}
{% load static %}

{% load crispy_forms_tags %}
{% block header %}

<link href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" rel="stylesheet" id="bootstrap-css">
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>

{% endblock %}
{% block head %}
<h3>View Products </h3>
{% endblock %}
{% block content %}


<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">View Product</h6>
            </div>
            <div class="card-body">
                <div class="container">
                  <table class="table table-bordered table-striped" id="view_product_datatable" width="100%" cellspacing="0">
                    <thead>
                      <tr>
                          <th>Name</th>
                          <th>Price</th>
                          <th>HSN</th>
                          <th>Tax</th>
                          <th style='display:none'>Description</th>
  
                      </tr>
                  </thead>
                  <tbody>
                  {% for eachproduct in allproducts.all %}
                      <tr>
                        <td class='productname'>{{ eachproduct.name}}</td>
                        <td class='productprice'>{{ eachproduct.price}}</td>
                        <td class='producthsn'>{{ eachproduct.HSN}}</td>
                        <td class='producttax'>{{ eachproduct.tax}}</td>
                        <td style='display:none'>{{ eachproduct.description}}</td>
                      </tr>
                      {% endfor %}
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
        </div>
  </div>
<!-- option modal -->
<div id="productModal" class="modal fade" role="dialog">
    <div class="modal-dialog  modal-sm">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Product Information</h4>
            </div>
            <div class="modal-body" style='text-align: center;overflow-y: scroll;'>
                <div class='container' style="width: 100%;">
                    <div class='row'>
                        <h4><b>Product Details for <span id='productname'></span> </b></h4>
                        <p><b>Price :</b>₹ <span id='productprice'></span></p>
                        <p><b>HSN:</b><span id='productHSN'></span></p>
                        <p><b>Description :</b><span id='productdescription'></span></p>
                        <p><b>Tax (%) :</b><span id='producttax'></span></p>
                    </div>
                    <hr>
                    <div class='row'>
                        <button type="button" class="btn btn-warning btn-lg btn-rounded " id='editid'></button>
                        <button type="button" class="btn btn-danger btn-lg btn-rounded " id='deleteid'></button>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>
<!-- Modal of Confirmation of delete -->
<div class="modal fade" id="confirmdeletemodal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content" style='height: 40%;'>
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">×</button>
                <h4 class="modal-title">Delete Customer </h4>
            </div>
            <div class="modal-body" style='text-align: center;'>
                <!-- <embed id='previewOfPdf' width='100%' height='100%' /> -->
                <button type="button" class="btn btn-danger" data-dismiss="modal">No</button>
                <button type="button" class="btn btn-primary" onclick='removedealer(selectedRowData)'>Yes</button><br>
                <!-- <small>Please note that entry regarding this delete will be store in servers</small> -->
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<script>

</script>





{% endblock %}
{% block scripts %}

<script src="{% static 'custom/js/product/viewproduct.js' %}"> </script>

</script>
{% endblock %}

mainapp/templates/product/editproduct.html
{% extends 'index.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h3> Edit Product </h3>
    {% if messages %}
  <ul class="messages">
    {% for message in messages %}
      <div class="alert alert-success fade in alert-dismissable" style="
    color: black;
">
<a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
<strong>Success!</strong> {{ message }}
                                    </div>
    {% endfor %}
  </ul>
{% endif %}
    <form method="POST">
    {% csrf_token %}
    <div class='row'>
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 col-xl-6">
     {{ productform.name|as_crispy_field }}
</div>
<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 col-xl-6">
               <div id='for_HSN' class="form-group has-warning has-feedback">

     {{ productform.HSN|as_crispy_field }}

                     <span id='for_HSN_symbol' class="ti-reload form-control-feedback"></span>
            </div>

</div>
</div>
    <div class='row'>
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 col-xl-6">
     {{ productform.price|as_crispy_field }}
</div>
<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 col-xl-6">
     {{ productform.tax|as_crispy_field }}
</div>
</div>
 <div class='row'>
 <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">

     {{ productform.description|as_crispy_field }}
</div>
</div>
     <div class='row'>
     <div class='form-group'>
            <button id='submitForm' type="submit" class="btn btn-primary btn-flat btn-addon m-b-10 m-l-5"><i
                    class="ti-plus"></i>Add Product </button>
        </div>
    </div>
    </form>
<script>
    $(document).ready(function() {
        // messages timeout for 10 sec 
     $("#for_HSN").on("keyup", function () {
    var input = $("#id_HSN").val()
    var string = 'SELECT "HSN" FROM public.mainapp_product where "HSN" = ' + input 
 document.getElementById('for_HSN').className = 'form-group has-warning has-feedback'
    document.getElementById('for_HSN_symbol').className = 'ti-reload form-control-feedback'

    $.get("/checkUserName/", { sqlParam: string }, function (data) {
        if (data.length != 0) {
            document.getElementById('for_HSN').className = 'form-group has-error has-feedback'
            document.getElementById('for_HSN_symbol').className = 'ti-close form-control-feedback'

        } else {
                document.getElementById('for_HSN').className = 'form-group has-success has-feedback'
                document.getElementById('for_HSN_symbol').className = 'ti-check form-control-feedback'
           
        }
    })

});

    });
</script>
{% endblock %}